FROM tensorflow/tensorflow
RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN pip3 install python-dotenv
RUN pip3 install flask
RUN pip3 install flickrapi
RUN pip3 install flask_cors
RUN pip3 install firebase-admin
RUN pip3 install pillow
RUN pip3 install sklearn
